' <auto-generated>
' Generated: 2026-01-21T20:14:52.207088Z
' Source: docs/_meta/methods.yml
' </auto-generated>

Option Strict On
Option Explicit On

Imports System.Diagnostics
Imports System.Reflection

Public Enum HelpTopic
    Home
    T2x2Table
    BoxAndWhiskers
    CochranSQTest
    CorrespondenceAnalysis
    CoxRegression
    DescriptiveStatistics
    FriedmanTest
    GeneralizedEstimatingEquationsGEE
    GeneralizedLinearModelsGLM
    Histogram
    HomogeneityOfVariance
    HotellingSTSquaredTest
    IndependentProporions
    KaplanMeierPlot
    KendallSRankCorrelation
    KruskalWallisTest
    LogrankTest
    MannWhitneyTest
    MantelHaenszelTest
    MultinomialLogisticRegression
    MultipleCorrespondenceAnalysis
    MultipleLinearRegressionLM
    NegativeBinomialRegressionNB2
    NormalPlot
    NormalityTests
    OneWayANOVA
    OneWayRepeatedMeasuresANOVA
    OrdinalLogisticRegression
    PairedSingleSampleTTests
    PairedTTest
    PrincipalComponentAnalysis
    Proportions
    ROCCurve
    RxCTable
    ScatterPlotMatrix
    SingleProportion
    SkillingsMackTest
    SpearmanRankCorrelation
    Symmetry
    TheilSenSimpleRegression
    TwoWayNestedANOVA
    UnivariateOutliers
    UnpairedTwoSampleTTests
    UnpairedTTest
    WilcoxonSignedRankTest
    XYZ3DScatterplot
    ZeroInflatedPoissonRegression
End Enum

Public Module HelpLinks
    Public Const BaseUrlRoot As String = "https://www.beshstat.eu/beshstatng/help"
    Public Const FallbackBaseUrl As String = BaseUrlRoot & "/latest/"

    ' Versioned base URL: /v<assembly version> (e.g. .../help/v1.3.0.12)
    Public ReadOnly Property BaseUrl As String
        Get
            Try
                Dim v = Assembly.GetExecutingAssembly().GetName().Version
                If v Is Nothing Then Return FallbackBaseUrl
                Dim ver = v.ToString()
                If String.IsNullOrWhiteSpace(ver) OrElse ver = "0.0.0.0" Then Return FallbackBaseUrl
                Return BaseUrlRoot & "/v" & ver
            Catch
                Return FallbackBaseUrl
            End Try
        End Get
    End Property

    Public Function GetUrl(topic As HelpTopic) As String
        Select Case topic
            Case HelpTopic.Home
                Return BaseUrl & "/"
            Case HelpTopic.T2x2Table
                Return BaseUrl & "/methods/2x2-table/"
            Case HelpTopic.BoxAndWhiskers
                Return BaseUrl & "/methods/box-and-whiskers/"
            Case HelpTopic.CochranSQTest
                Return BaseUrl & "/methods/cochrans-q-test/"
            Case HelpTopic.CorrespondenceAnalysis
                Return BaseUrl & "/methods/correspondence-analysis/"
            Case HelpTopic.CoxRegression
                Return BaseUrl & "/methods/cox-regression/"
            Case HelpTopic.DescriptiveStatistics
                Return BaseUrl & "/methods/descriptive-statistics/"
            Case HelpTopic.FriedmanTest
                Return BaseUrl & "/methods/friedman-test/"
            Case HelpTopic.GeneralizedEstimatingEquationsGEE
                Return BaseUrl & "/methods/generalized-estimating-equations-gee/"
            Case HelpTopic.GeneralizedLinearModelsGLM
                Return BaseUrl & "/methods/generalized-linear-models-glm/"
            Case HelpTopic.Histogram
                Return BaseUrl & "/methods/histogram/"
            Case HelpTopic.HomogeneityOfVariance
                Return BaseUrl & "/methods/homogeneity-of-variance/"
            Case HelpTopic.HotellingSTSquaredTest
                Return BaseUrl & "/methods/hotellings-t-squared-test/"
            Case HelpTopic.IndependentProporions
                Return BaseUrl & "/methods/sample-size-independent-proporions/"
            Case HelpTopic.KaplanMeierPlot
                Return BaseUrl & "/methods/kaplan-meier-plot/"
            Case HelpTopic.KendallSRankCorrelation
                Return BaseUrl & "/methods/kendalls-rank-correlation/"
            Case HelpTopic.KruskalWallisTest
                Return BaseUrl & "/methods/kruskal-wallis-test/"
            Case HelpTopic.LogrankTest
                Return BaseUrl & "/methods/logrank-test/"
            Case HelpTopic.MannWhitneyTest
                Return BaseUrl & "/methods/mann-whitney-test/"
            Case HelpTopic.MantelHaenszelTest
                Return BaseUrl & "/methods/mantel-haenszel-test/"
            Case HelpTopic.MultinomialLogisticRegression
                Return BaseUrl & "/methods/multinomial-logistic-regression/"
            Case HelpTopic.MultipleCorrespondenceAnalysis
                Return BaseUrl & "/methods/multiple-correspondence-analysis/"
            Case HelpTopic.MultipleLinearRegressionLM
                Return BaseUrl & "/methods/multiple-linear-regression-lm/"
            Case HelpTopic.NegativeBinomialRegressionNB2
                Return BaseUrl & "/methods/negative-binomial-regression-nb2/"
            Case HelpTopic.NormalPlot
                Return BaseUrl & "/methods/normal-plot/"
            Case HelpTopic.NormalityTests
                Return BaseUrl & "/methods/normality-tests/"
            Case HelpTopic.OneWayANOVA
                Return BaseUrl & "/methods/one-way-anova/"
            Case HelpTopic.OneWayRepeatedMeasuresANOVA
                Return BaseUrl & "/methods/one-way-repeated-measures-anova/"
            Case HelpTopic.OrdinalLogisticRegression
                Return BaseUrl & "/methods/ordinal-logistic-regression/"
            Case HelpTopic.PairedSingleSampleTTests
                Return BaseUrl & "/methods/paired-t-tests/"
            Case HelpTopic.PairedTTest
                Return BaseUrl & "/methods/sample-size-paired-t-test/"
            Case HelpTopic.PrincipalComponentAnalysis
                Return BaseUrl & "/methods/principal-component-analysis/"
            Case HelpTopic.Proportions
                Return BaseUrl & "/methods/proportions/"
            Case HelpTopic.ROCCurve
                Return BaseUrl & "/methods/roc-curve/"
            Case HelpTopic.RxCTable
                Return BaseUrl & "/methods/rxc-table/"
            Case HelpTopic.ScatterPlotMatrix
                Return BaseUrl & "/methods/scatter-plot-matrix/"
            Case HelpTopic.SingleProportion
                Return BaseUrl & "/methods/sample-size-single-proportion/"
            Case HelpTopic.SkillingsMackTest
                Return BaseUrl & "/methods/skillings-mack-test/"
            Case HelpTopic.SpearmanRankCorrelation
                Return BaseUrl & "/methods/spearman-rank-correlation/"
            Case HelpTopic.Symmetry
                Return BaseUrl & "/methods/symmetry/"
            Case HelpTopic.TheilSenSimpleRegression
                Return BaseUrl & "/methods/theil-sen-simple-regression/"
            Case HelpTopic.TwoWayNestedANOVA
                Return BaseUrl & "/methods/two-way-nested-anova/"
            Case HelpTopic.UnivariateOutliers
                Return BaseUrl & "/methods/univariate-outliers/"
            Case HelpTopic.UnpairedTwoSampleTTests
                Return BaseUrl & "/methods/unpaired-two-sample-t-tests/"
            Case HelpTopic.UnpairedTTest
                Return BaseUrl & "/methods/sample-size-unpaired-t-test/"
            Case HelpTopic.WilcoxonSignedRankTest
                Return BaseUrl & "/methods/wilcoxon-signed-rank-test/"
            Case HelpTopic.XYZ3DScatterplot
                Return BaseUrl & "/methods/xyz-3d-scatterplot/"
            Case HelpTopic.ZeroInflatedPoissonRegression
                Return BaseUrl & "/methods/zero-inflated-poisson-regression/"
            Case Else
                Return FallbackBaseUrl
        End Select
    End Function

    Public Sub OpenTopic(topic As HelpTopic)
        OpenUrl(GetUrl(topic))
    End Sub

    Public Sub OpenUrl(url As String)
        If String.IsNullOrWhiteSpace(url) Then url = FallbackBaseUrl
        Dim psi As New ProcessStartInfo(url) With {.UseShellExecute = True}
        Process.Start(psi)
    End Sub
End Module
