' <auto-generated>
' Generated: 2026-03-18T16:47:37.187744Z
' Source: docs/_meta/methods.yml
' </auto-generated>

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.Windows.Forms

Public Module HelpContext
    ' Resolution order:
    '   1) frm.Tag as HelpTopic (or String enum name)
    '   2) (Form class + frm.Text) using the generated map
    '   3) fallback Home (BaseUrl)

    Private ReadOnly FormTitleMap As New Dictionary(Of String, HelpTopic)(StringComparer.OrdinalIgnoreCase) From {
        {"Ui0OneRefeditMulticol|cochran s q test", HelpTopic.CochranSQTest},
        {"Ui0OneRefeditMulticol|correspondence analysis", HelpTopic.CorrespondenceAnalysis},
        {"Ui0OneRefeditMulticol|friedman test", HelpTopic.FriedmanTest},
        {"Ui0OneRefeditMulticol|intraclass correlation coefficients", HelpTopic.IntraclassCorrelationCoefficients},
        {"Ui0OneRefeditMulticol|mantel haenszel test", HelpTopic.MantelHaenszelTest},
        {"Ui0OneRefeditMulticol|one way repeated measures anova", HelpTopic.OneWayRepeatedMeasuresANOVA},
        {"Ui0OneRefeditMulticol|rxc table", HelpTopic.RxCTable},
        {"Ui0OneRefeditMulticol|skillings mack test", HelpTopic.SkillingsMackTest},
        {"Ui11PCA|multiple correspondence analysis", HelpTopic.MultipleCorrespondenceAnalysis},
        {"Ui11PCA|principal component analysis", HelpTopic.PrincipalComponentAnalysis},
        {"Ui11PCA|scatter plot matrix", HelpTopic.ScatterPlotMatrix},
        {"Ui12SampleSizeTtestSingleProp|sample size independent proportions", HelpTopic.IndependentProporions},
        {"Ui12SampleSizeTtestSingleProp|sample size paired t test", HelpTopic.PairedTTest},
        {"Ui12SampleSizeTtestSingleProp|sample size single proportion", HelpTopic.SingleProportion},
        {"Ui12SampleSizeTtestSingleProp|sample size unpaired t test", HelpTopic.UnpairedTTest},
        {"Ui13GEE|generalized estimating equations", HelpTopic.GeneralizedEstimatingEquationsGEE},
        {"Ui3XYZplot|xyz 3d scatterplot", HelpTopic.XYZ3DScatterplot},
        {"Ui4Cox|cox regression", HelpTopic.CoxRegression},
        {"Ui4KMandLogRank|kaplan meier plot", HelpTopic.KaplanMeierPlot},
        {"Ui4KMandLogRank|logrank test", HelpTopic.LogrankTest},
        {"Ui82x2|2x2 table", HelpTopic.T2x2Table},
        {"Ui8Proportions|proportions", HelpTopic.Proportions},
        {"Ui99ExportChart|export chart", HelpTopic.ExportChart},
        {"Ui9ANOVA2nested|passing bablok regression", HelpTopic.PassingBablokRegression},
        {"Ui9ANOVA2nested|two way nested anova", HelpTopic.TwoWayNestedANOVA},
        {"UiGLM|generalized linear models", HelpTopic.GeneralizedLinearModelsGLM},
        {"UiGLM|multinomial logistic regression", HelpTopic.MultinomialLogisticRegression},
        {"UiGLM|multiple linear regression lm", HelpTopic.MultipleLinearRegressionLM},
        {"UiGLM|negative binomial regression nb2", HelpTopic.NegativeBinomialRegressionNB2},
        {"UiGLM|ordinal logistic regression", HelpTopic.OrdinalLogisticRegression},
        {"UiGLM|zero inflated poisson regression", HelpTopic.ZeroInflatedPoissonRegression},
        {"UiTwoInputRefedits|deming regression", HelpTopic.DemingRegression},
        {"UiTwoInputRefedits|hotelling s t squared test", HelpTopic.HotellingSTSquaredTest},
        {"UiTwoInputRefedits|kendall s rank correlation", HelpTopic.KendallSRankCorrelation},
        {"UiTwoInputRefedits|paired t test", HelpTopic.PairedSingleSampleTTests},
        {"UiTwoInputRefedits|spearman rank correlation", HelpTopic.SpearmanRankCorrelation},
        {"UiTwoInputRefedits|theil sen simple regression", HelpTopic.TheilSenSimpleRegression},
        {"UiTwoInputRefedits|wilcoxon signed rank test", HelpTopic.WilcoxonSignedRankTest},
        {"UibyID|box and whiskers", HelpTopic.BoxAndWhiskers},
        {"UibyID|descriptive statistcs", HelpTopic.DescriptiveStatistics},
        {"UibyID|histogram", HelpTopic.Histogram},
        {"UibyID|homogeneity of variance", HelpTopic.HomogeneityOfVariance},
        {"UibyID|kruskal wallis test", HelpTopic.KruskalWallisTest},
        {"UibyID|mann whitney test", HelpTopic.MannWhitneyTest},
        {"UibyID|normal plot", HelpTopic.NormalPlot},
        {"UibyID|normality", HelpTopic.NormalityTests},
        {"UibyID|one way anova", HelpTopic.OneWayANOVA},
        {"UibyID|outliers", HelpTopic.UnivariateOutliers},
        {"UibyID|roc curve", HelpTopic.ROCCurve},
        {"UibyID|symmetry", HelpTopic.Symmetry},
        {"UibyID|unpaired t test", HelpTopic.UnpairedTwoSampleTTests}
    }

    Public Function ResolveTopic(frm As Form) As HelpTopic
        If frm Is Nothing Then Return HelpTopic.Home

        ' 1) Explicit override (best if you ever need it)
        If frm.Tag IsNot Nothing Then
            If TypeOf frm.Tag Is HelpTopic Then Return DirectCast(frm.Tag, HelpTopic)
            If TypeOf frm.Tag Is String Then
                Dim s = DirectCast(frm.Tag, String)
                Dim t As HelpTopic
                If [Enum].TryParse(Of HelpTopic)(s, True, t) Then Return t
            End If
        End If

        ' 2) Form class + title
        Dim formName = frm.GetType().Name
        Dim titleKey = Normalize(frm.Text)
        Dim k = formName & "|" & titleKey
        Dim topic As HelpTopic
        If FormTitleMap.TryGetValue(k, topic) Then Return topic

        ' Allow class-only match (empty title)
        Dim k2 = formName & "|"
        If FormTitleMap.TryGetValue(k2, topic) Then Return topic

        Return HelpTopic.Home
    End Function

    Public Sub OpenHelp(frm As Form)
        Dim topic = ResolveTopic(frm)
        HelpLinks.OpenTopic(topic)
    End Sub

    Private Function Normalize(s As String) As String
        If String.IsNullOrWhiteSpace(s) Then Return ""
        s = s.Trim().ToLowerInvariant()
        s = s.Replace("–", " ").Replace("—", " ").Replace("-", " ")
        Dim sb As New System.Text.StringBuilder(s.Length)
        For Each ch As Char In s
            If Char.IsLetterOrDigit(ch) Then
                sb.Append(ch)
            Else
                sb.Append(" "c)
            End If
        Next
        Dim collapsed = System.Text.RegularExpressions.Regex.Replace(sb.ToString(), "\s+", " ").Trim()
        Return collapsed
    End Function
End Module
