# ==============================================================================
# kr_lmm_sleepstudy_unbalanced_krmodcomp_reference.R
# ==============================================================================
# Purpose:
#   Generate pbkrtest KR reference constants for the existing unbalanced
#   sleepstudy random-intercept/random-slope LMM test data.
#
# Input:
#   TestData/mixedmodel_lmm_sleepstudy_random_slope_unbalanced_data.csv
#
# Output:
#   - CSV exports in kr_reference_outputs/
#   - ready-to-paste VB constants printed to the console
#
# Notes:
#   This script intentionally does not create any additional test data.
#   It uses lme4 + pbkrtest.  The script prints package versions so the VB
#   test comments can record the exact reference versions.
# ==============================================================================

required <- c("lme4", "pbkrtest")
missing <- required[!vapply(required, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing) > 0) {
  stop("Install required packages first: ", paste(missing, collapse = ", "))
}

ver_lme4 <- as.character(utils::packageVersion("lme4"))
ver_pbkrtest <- as.character(utils::packageVersion("pbkrtest"))
message("lme4 version: ", ver_lme4)
message("pbkrtest version: ", ver_pbkrtest)

root <- normalizePath(getwd(), winslash = "/", mustWork = FALSE)
data_path <- file.path(root, "TestData", "mixedmodel_lmm_sleepstudy_random_slope_unbalanced_data.csv")
if (!file.exists(data_path)) {
  data_path <- file.path(root, "mixedmodel_lmm_sleepstudy_random_slope_unbalanced_data.csv")
}
if (!file.exists(data_path)) {
  stop("Could not find mixedmodel_lmm_sleepstudy_random_slope_unbalanced_data.csv")
}

out_dir <- file.path(root, "kr_reference_outputs")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

dat <- read.csv(data_path, stringsAsFactors = FALSE)
dat$subject <- factor(dat$subject)
dat$days <- as.numeric(dat$days)
dat$reaction <- as.numeric(dat$reaction)

fit <- lme4::lmer(reaction ~ days + (days | subject), data = dat, REML = TRUE)

vc0 <- as.matrix(vcov(fit))
vc_kr <- as.matrix(pbkrtest::vcovAdj(fit))
beta <- lme4::fixef(fit)

coef_tab <- data.frame(
  effect = names(beta),
  beta = as.numeric(beta),
  ordinary_se = sqrt(diag(vc0)),
  kr_adjusted_se = sqrt(diag(vc_kr)),
  stringsAsFactors = FALSE
)

# Single-coefficient KRmodcomp restriction-matrix tests.
single_rows <- list()
for (i in seq_along(beta)) {
  L <- matrix(0, nrow = 1, ncol = length(beta))
  colnames(L) <- names(beta)
  rownames(L) <- names(beta)[i]
  L[1, i] <- 1

  kr <- pbkrtest::KRmodcomp(fit, L)
  st <- kr$stats

  single_rows[[length(single_rows) + 1L]] <- data.frame(
    effect = names(beta)[i],
    ndf = as.numeric(st$ndf),
    ddf = as.numeric(st$ddf),
    fstat = as.numeric(st$Fstat),
    f_scaling = as.numeric(st$F.scaling),
    fstat_scaled = as.numeric(st$FstatU),
    p_value = as.numeric(st$p.value),
    stringsAsFactors = FALSE
  )
}

single_df <- do.call(rbind, single_rows)
coef_with_tests <- merge(coef_tab, single_df, by = "effect", all.x = TRUE)

write.csv(coef_with_tests,
          file.path(out_dir, "r_lmm_sleepstudy_unbalanced_kr_coefficients_and_tests.csv"),
          row.names = FALSE)

vc_long <- data.frame(
  row_index = rep(seq_len(nrow(vc_kr)), each = ncol(vc_kr)),
  col_index = rep(seq_len(ncol(vc_kr)), times = nrow(vc_kr)),
  row_name = rep(rownames(vc_kr), each = ncol(vc_kr)),
  col_name = rep(colnames(vc_kr), times = nrow(vc_kr)),
  kr_adjusted_varbeta = as.vector(t(vc_kr)),
  stringsAsFactors = FALSE
)

write.csv(vc_long,
          file.path(out_dir, "r_lmm_sleepstudy_unbalanced_kr_vcov.csv"),
          row.names = FALSE)

cat("\n' Paste into a VB GetHardCodedRReferenceRows() function.\n")
cat("' Generated by kr_lmm_sleepstudy_unbalanced_krmodcomp_reference.R\n")
cat("' R package versions: lme4 ", ver_lme4, ", pbkrtest ", ver_pbkrtest, "\n", sep = "")
cat("Return New List(Of RReferenceRow) From {\n")
for (i in seq_len(nrow(coef_with_tests))) {
  comma <- if (i < nrow(coef_with_tests)) "," else ""
  cat(sprintf(
    "    New RReferenceRow(effect:=\"%s\", beta:=%.12g, ordinarySE:=%.12g, krAdjustedSE:=%.12g)%s\n",
    coef_with_tests$effect[i],
    coef_with_tests$beta[i],
    coef_with_tests$ordinary_se[i],
    coef_with_tests$kr_adjusted_se[i],
    comma
  ))
}
cat("}\n\n")

utils::sessionInfo()
