#!/usr/bin/env python3
"""Generate VB.NET help link mapping from MkDocs metadata (methods.yml).

Source of truth: docs/_meta/methods.yml

Outputs (written into the VB project):
  - src/Help/HelpLinks.vb   (HelpTopic enum + URL builder)
  - src/Help/HelpContext.vb (Resolve help topic from Form.Tag or Form.Text)

Fix vs older generator:
  - Context resolution now uses (FormClassName + normalized Form.Text), so dialogs that share
    the same caption (e.g. "Paired T-test" analysis vs "Paired T-test" sample-size) resolve correctly.
  - If ambiguous/unresolved, falls back to Home (BaseUrl).

Usage:
  python tools/generate_help_links.py --methods-yml "..\BESHStatNG_Help_MkDocs\docs\_meta\methods.yml" --project-dir ".."

Dependencies:
  pip install pyyaml
"""

import argparse
import datetime
import re
import sys
from pathlib import Path

try:
    import yaml  # type: ignore
except ImportError:
    print("Missing dependency: pyyaml. Install with: pip install pyyaml")
    sys.exit(2)


def vb_ident(name: str) -> str:
    """Make a safe VB identifier (enum member)."""
    s = re.sub(r"[^A-Za-z0-9_]", "", name or "")
    if not s:
        s = "Unknown"
    if s[0].isdigit():
        s = "_" + s
    return s


def normalize_for_key(s: str | None) -> str:
    """Normalize titles into a stable lookup key (lowercase, punctuation/whitespace collapsed)."""
    if not s:
        return ""
    s = s.strip().lower()
    # normalize dash variants
    s = s.replace("–", " ").replace("—", " ").replace("-", " ")
    # keep only letters/digits as tokens
    s = re.sub(r"[^a-z0-9]+", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def load_methods(meta: dict) -> list[dict]:
    """Supports either meta['methods'] or older category shapes."""
    if isinstance(meta.get("methods"), list):
        return meta["methods"]
    # fallback: categories/items style
    out: list[dict] = []
    if isinstance(meta.get("categories"), list):
        for c in meta["categories"]:
            out.extend(c.get("items", []) or [])
    return out


def load_pages(meta: dict) -> list[dict]:
    """Load non-method pages that still need help hooks (e.g. export-chart.md)."""
    pages = meta.get("pages")
    return pages if isinstance(pages, list) else []


def generate(methods_yml: Path, project_dir: Path) -> None:
    meta = yaml.safe_load(methods_yml.read_text(encoding="utf-8"))
    base_url = (meta.get("site", {}) or {}).get("baseUrl", "https://www.beshstat.eu/beshstatng/help").rstrip("/")
    methods = load_methods(meta)
    pages = load_pages(meta)

    # 1) Build HelpTopic enum + URL mapping
    topics: list[tuple[str, str]] = [("Home", "/")]

    # Method pages live under /methods/<slug>/
    for m in methods:
        key = m.get("key")
        slug = m.get("slug")
        if not key or not slug:
            continue
        topics.append((vb_ident(key), f"/methods/{slug}/"))

    # Non-method pages live at /<slug>/ (MkDocs page "export-chart.md" -> "/export-chart/")
    for p in pages:
        key = p.get("key")
        slug = p.get("slug")
        if not key or not slug:
            continue
        rel = slug if slug.startswith("/") else f"/{slug}/"
        if not rel.endswith("/"):
            rel += "/"
        topics.append((vb_ident(key), rel))

    # de-dupe by enum name (stable order)
    seen: set[str] = set()
    uniq_topics: list[tuple[str, str]] = []
    for k, rel in topics:
        if k in seen:
            continue
        seen.add(k)
        uniq_topics.append((k, rel))

    # 2) Build context mapping using (FormClassName + Form.Text)
    #    Key format: "FormClass|normalized_title"
    mapping: dict[str, str] = {}      # key -> HelpTopicName
    conflicts: set[str] = set()

    for m in methods:
        topic = vb_ident(m.get("key", ""))
        title = m.get("title") or ""
        for fr in (m.get("forms") or []):
            form = fr.get("form") or ""
            # use analysisTitle (preferred) else method title
            disp = fr.get("analysisTitle") or title
            map_key = f"{form}|{normalize_for_key(disp)}"
            if map_key in mapping and mapping[map_key] != topic:
                conflicts.add(map_key)
            else:
                mapping[map_key] = topic

    for p in pages:
        topic = vb_ident(p.get("key", ""))
        title = p.get("title") or ""
        for fr in (p.get("forms") or []):
            form = fr.get("form") or ""
            disp = fr.get("analysisTitle") or title
            map_key = f"{form}|{normalize_for_key(disp)}"
            if map_key in mapping and mapping[map_key] != topic:
                conflicts.add(map_key)
            else:
                mapping[map_key] = topic


    # remove ambiguous keys -> will fall back to Home
    for k in conflicts:
        mapping.pop(k, None)

    gen_time = datetime.datetime.utcnow().isoformat() + "Z"

    # ---- HelpLinks.vb ----
    help_links_vb: list[str] = []
    help_links_vb += [
        "' <auto-generated>",
        f"' Generated: {gen_time}",
        "' Source: docs/_meta/methods.yml",
        "' </auto-generated>",
        "",
        "Option Strict On",
        "Option Explicit On",
        "",
        "Imports System.Diagnostics",
        "Imports System.Reflection",
        "Imports System.Net",
        "Imports System.Collections.Generic",
        "",
        "Public Enum HelpTopic",
    ]
    for k, _ in uniq_topics:
        help_links_vb.append(f"    {k}")
    help_links_vb += [
        "End Enum",
        "",
        "Public Module HelpLinks",
        f"    Public Const BaseUrlRoot As String = \"{base_url}\"",
        "    Public Const FallbackBaseUrl As String = BaseUrlRoot & \"/latest/\"",
        "",
        "    ' Versioned base URL: /v<assembly version> (e.g. .../help/v1.3.0.12)",
        "    Public ReadOnly Property BaseUrl As String",
        "        Get",
        "            Try",
        "                Dim v = Assembly.GetExecutingAssembly().GetName().Version",
        "                If v Is Nothing Then Return FallbackBaseUrl",
        "                Dim ver = v.ToString()",
        "                If String.IsNullOrWhiteSpace(ver) OrElse ver = \"0.0.0.0\" Then Return FallbackBaseUrl",
        "                Return BaseUrlRoot & \"/v\" & ver",
        "            Catch",
        "                Return FallbackBaseUrl",
        "            End Try",
        "        End Get",
        "    End Property",
        "",
        "    Public Function GetUrl(topic As HelpTopic) As String",
        "        Select Case topic",
    ]
    for k, rel in uniq_topics:
        help_links_vb += [
            f"            Case HelpTopic.{k}",
            f"                Return BaseUrl & \"{rel}\"",
        ]
    help_links_vb += [
        "            Case Else",
        "                Return FallbackBaseUrl",
        "        End Select",
        "    End Function",
        "",
        "    ' Cache URL existence results to avoid repeated network requests",
        "    Private ReadOnly _urlExistsCache As New Dictionary(Of String, Boolean)(StringComparer.OrdinalIgnoreCase)",
        "",
        "    Public Sub OpenTopic(topic As HelpTopic)",
        "        OpenUrlWithFallback(GetUrl(topic))",
        "    End Sub",
        "",
        "    Public Sub OpenUrl(url As String)",
        "        If String.IsNullOrWhiteSpace(url) Then url = FallbackBaseUrl",
        "        Dim psi As New ProcessStartInfo(url) With {.UseShellExecute = True}",
        "        Process.Start(psi)",
        "    End Sub",
        "",
        "    Private Sub OpenUrlWithFallback(primaryUrl As String)",
        "        If String.IsNullOrWhiteSpace(primaryUrl) Then",
        "            OpenUrl(FallbackBaseUrl)",
        "            Return",
        "        End If",
        "",
        "        ' 1) Try versioned URL first",
        "        If UrlExistsCached(primaryUrl) Then",
        "            OpenUrl(primaryUrl)",
        "            Return",
        "        End If",
        "",
        "        ' 2) Try same relative path under /latest/",
        "        Dim fallbackCandidate As String = BuildFallbackCandidate(primaryUrl)",
        "        If Not String.IsNullOrWhiteSpace(fallbackCandidate) AndAlso UrlExistsCached(fallbackCandidate) Then",
        "            OpenUrl(fallbackCandidate)",
        "            Return",
        "        End If",
        "",
        "        ' 3) Last resort: open the fallback base",
        "        OpenUrl(FallbackBaseUrl)",
        "    End Sub",
        "",
        "    Private Function BuildFallbackCandidate(primaryUrl As String) As String",
        "        ' Preserve relative path when switching from /vX.Y.Z.W to /latest/",
        "        Try",
        "            Dim baseV As String = BaseUrl",
        "            If String.IsNullOrWhiteSpace(baseV) Then Return Nothing",
        "            If primaryUrl.StartsWith(baseV, StringComparison.OrdinalIgnoreCase) Then",
        "                Dim rel As String = primaryUrl.Substring(baseV.Length)",
        "                Dim fb As String = FallbackBaseUrl.TrimEnd(\"/\"c)",
        "                If Not rel.StartsWith(\"/\", StringComparison.Ordinal) Then rel = \"/\" & rel",
        "                Return fb & rel",
        "            End If",
        "        Catch",
        "        End Try",
        "        Return Nothing",
        "    End Function",
        "",
        "    Private Function UrlExistsCached(url As String) As Boolean",
        "        Dim exists As Boolean",
        "        If _urlExistsCache.TryGetValue(url, exists) Then Return exists",
        "        exists = UrlExists(url)",
        "        _urlExistsCache(url) = exists",
        "        Return exists",
        "    End Function",
        "",
        "    Private Function UrlExists(url As String) As Boolean",
        "        ' Use GET and sniff HTML because some hosting returns HTTP 200 for the MkDocs 404 page.",
        "        Try",
        "            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 Or SecurityProtocolType.Tls11 Or SecurityProtocolType.Tls",
        "        Catch",
        "        End Try",
        "",
        "        Try",
        "            Dim req = CType(WebRequest.Create(url), HttpWebRequest)",
        "            req.Method = \"GET\"",
        "            req.AllowAutoRedirect = True",
        "            req.Timeout = 2000",
        "            req.ReadWriteTimeout = 2000",
        "            req.UserAgent = \"BESHStatNG-Help\"",
        "            req.Accept = \"text/html\"",
        "            ' Try to read only a small portion of the response",
        "            Try : req.AddRange(0, 8191) : Catch : End Try",
        "",
        "            Using resp = CType(req.GetResponse(), HttpWebResponse)",
        "                Dim code As Integer = CInt(resp.StatusCode)",
        "                If code = 404 OrElse code = 410 Then Return False",
        "                If code < 200 OrElse code >= 400 Then Return False",
        "",
        "                Using s = resp.GetResponseStream()",
        "                    If s Is Nothing Then Return False",
        "                    Using sr As New IO.StreamReader(s, System.Text.Encoding.UTF8, detectEncodingFromByteOrderMarks:=True, bufferSize:=4096)",
        "                        Dim html As String = sr.ReadToEnd()",
        "                        If String.IsNullOrEmpty(html) Then Return True",
        "                        Dim h As String = html.ToLowerInvariant()",
        "",
        "                        ' MkDocs Material 404 markers",
        "                        If h.Contains(\"oops! that page\") OrElse",
        "                            (h.Contains(\"page can\") AndAlso h.Contains(\"t be found\")) OrElse",
        "                            h.Contains(\"404 - not found\") OrElse",
        "                            h.Contains(\">404<\") Then",
        "                            Return False",
        "                        End If",
        "",
        "                        Return True",
        "                    End Using",
        "                End Using",
        "            End Using",
        "",
        "        Catch ex As WebException",
        "            Dim resp = TryCast(ex.Response, HttpWebResponse)",
        "            If resp IsNot Nothing Then",
        "                Dim code As Integer = CInt(resp.StatusCode)",
        "                If code = 404 OrElse code = 410 Then Return False",
        "                Return False",
        "            End If",
        "            Return False",
        "        Catch",
        "            Return False",
        "        End Try",
        "    End Function",
        "End Module",
        "",
    ]

    # ---- HelpContext.vb ----
    help_context_vb: list[str] = []
    help_context_vb += [
        "' <auto-generated>",
        f"' Generated: {gen_time}",
        "' Source: docs/_meta/methods.yml",
        "' </auto-generated>",
        "",
        "Option Strict On",
        "Option Explicit On",
        "",
        "Imports System",
        "Imports System.Collections.Generic",
        "Imports System.Windows.Forms",
        "",
        "Public Module HelpContext",
        "    ' Resolution order:",
        "    '   1) frm.Tag as HelpTopic (or String enum name)",
        "    '   2) (Form class + frm.Text) using the generated map",
        "    '   3) fallback Home (BaseUrl)",
        "",
        "    Private ReadOnly FormTitleMap As New Dictionary(Of String, HelpTopic)(StringComparer.OrdinalIgnoreCase) From {",
    ]

    # emit map
    map_items = []
    for key, topic in sorted(mapping.items()):
        if not key.endswith("|"):  # allow empty title keys too, if any
            map_items.append(f"        {{\"{key}\", HelpTopic.{topic}}}")
        else:
            map_items.append(f"        {{\"{key}\", HelpTopic.{topic}}}")
    help_context_vb.append(",\n".join(map_items) if map_items else "        {\"\", HelpTopic.Home}")
    help_context_vb += [
        "    }",
        "",
        "    Public Function ResolveTopic(frm As Form) As HelpTopic",
        "        If frm Is Nothing Then Return HelpTopic.Home",
        "",
        "        ' 1) Explicit override (best if you ever need it)",
        "        If frm.Tag IsNot Nothing Then",
        "            If TypeOf frm.Tag Is HelpTopic Then Return DirectCast(frm.Tag, HelpTopic)",
        "            If TypeOf frm.Tag Is String Then",
        "                Dim s = DirectCast(frm.Tag, String)",
        "                Dim t As HelpTopic",
        "                If [Enum].TryParse(Of HelpTopic)(s, True, t) Then Return t",
        "            End If",
        "        End If",
        "",
        "        ' 2) Form class + title",
        "        Dim formName = frm.GetType().Name",
        "        Dim titleKey = Normalize(frm.Text)",
        "        Dim k = formName & \"|\" & titleKey",
        "        Dim topic As HelpTopic",
        "        If FormTitleMap.TryGetValue(k, topic) Then Return topic",
        "",
        "        ' Allow class-only match (empty title)",
        "        Dim k2 = formName & \"|\"",
        "        If FormTitleMap.TryGetValue(k2, topic) Then Return topic",
        "",
        "        Return HelpTopic.Home",
        "    End Function",
        "",
        "    Public Sub OpenHelp(frm As Form)",
        "        Dim topic = ResolveTopic(frm)",
        "        HelpLinks.OpenTopic(topic)",
        "    End Sub",
        "",
        "    Private Function Normalize(s As String) As String",
        "        If String.IsNullOrWhiteSpace(s) Then Return \"\"",
        "        s = s.Trim().ToLowerInvariant()",
        "        s = s.Replace(\"–\", \" \").Replace(\"—\", \" \").Replace(\"-\", \" \")",
        "        Dim sb As New System.Text.StringBuilder(s.Length)",
        "        For Each ch As Char In s",
        "            If Char.IsLetterOrDigit(ch) Then",
        "                sb.Append(ch)",
        "            Else",
        "                sb.Append(\" \"c)",
        "            End If",
        "        Next",
        "        Dim collapsed = System.Text.RegularExpressions.Regex.Replace(sb.ToString(), \"\\s+\", \" \").Trim()",
        "        Return collapsed",
        "    End Function",
        "End Module",
        "",
    ]

    out_dir = project_dir / "src" / "Help"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "HelpLinks.vb").write_text("\n".join(help_links_vb), encoding="utf-8", newline="\n")
    (out_dir / "HelpContext.vb").write_text("\n".join(help_context_vb), encoding="utf-8", newline="\n")

    print(f"Wrote {out_dir / 'HelpLinks.vb'}")
    print(f"Wrote {out_dir / 'HelpContext.vb'}")
    if conflicts:
        print(f"WARNING: {len(conflicts)} ambiguous Form+Title keys were skipped (will fall back to Home).")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--methods-yml", required=True, help="Path to docs/_meta/methods.yml")
    ap.add_argument("--project-dir", default=".", help="VB project root directory")
    args = ap.parse_args()

    methods_yml = Path(args.methods_yml).resolve()
    project_dir = Path(args.project_dir).resolve()

    if not methods_yml.exists():
        raise SystemExit(f"methods.yml not found: {methods_yml}")

    generate(methods_yml, project_dir)


if __name__ == "__main__":
    main()
