' <auto-generated>
' Generated: 2026-08-23T12:38:22.564810+00:00
' Source: docs/_meta/methods.yml
' </auto-generated>

Option Strict On
Option Explicit On

Imports System.Diagnostics
Imports System.Reflection
Imports System.Net
Imports System.Collections.Generic

Public Enum HelpTopic
    Home
    T2x2Table
    BoxAndWhiskers
    CategoricalHistogram
    CochranSQTest
    ControlCharts
    ConvexHull
    CorrespondenceAnalysis
    CoxRegression
    DescriptiveStatistics
    DiscriminantAnalysis
    FactorAnalysis
    FriedmanTest
    GeneralizedEstimatingEquationsGEE
    GeneralizedLinearModelsGLM
    HierarchicalClustering
    Histogram
    HomogeneityOfVariance
    HotellingSTSquaredTest
    IndependentProportions
    KaplanMeierPlot
    KendallSRankCorrelation
    KiteChart
    KMeansClustering
    KruskalWallisTest
    LogrankTest
    MannWhitneyTest
    MantelHaenszelTest
    MultinomialLogisticRegression
    MultipleCorrespondenceAnalysis
    MultipleLinearRegressionLM
    MultivariateControlCharts
    NegativeBinomialRegressionNB2
    NormalPlot
    NormalityTests
    OneWayANOVA
    OneWayRepeatedMeasuresANOVA
    OrdinalLogisticRegression
    MixedModelsForRepeatedMeasuresMMRM
    LinearMixedModelsLMM
    PropensityScoreMatching
    PairedSingleSampleTTests
    PairedTTest
    Polarplot
    PrincipalComponentAnalysis
    Proportions
    ROCCurve
    RxCTable
    ScatterPlotMatrix
    SSlogrank
    SingleProportion
    SkillingsMackTest
    SpearmanRankCorrelation
    Symmetry
    TheilSenSimpleRegression
    TwoWayNestedANOVA
    UnivariateOutliers
    UnpairedTwoSampleTTests
    UnpairedTTest
    SScox
    SSicc
    SSblandaltman
    ViolinPlot
    WilcoxonSignedRankTest
    XYZ3DScatterplot
    ZeroInflatedPoissonRegression
    PassingBablokRegression
    DemingRegression
    BlandAltman
    LinsCCC
    CohensKappa
    IntraclassCorrelationCoefficients
    ExportChart
    GlobalSettings
End Enum

Public Module HelpLinks
    Public Const BaseUrlRoot As String = "https://www.beshstat.eu/beshstatng/help"
    Public Const FallbackBaseUrl As String = BaseUrlRoot & "/latest/"

    ' Versioned base URL: /v<assembly version> (e.g. .../help/v1.3.0.12)
    Public ReadOnly Property BaseUrl As String
        Get
            Try
                Dim v = Assembly.GetExecutingAssembly().GetName().Version
                If v Is Nothing Then Return FallbackBaseUrl
                Dim ver = v.ToString()
                If String.IsNullOrWhiteSpace(ver) OrElse ver = "0.0.0.0" Then Return FallbackBaseUrl
                Return BaseUrlRoot & "/v" & ver
            Catch
                Return FallbackBaseUrl
            End Try
        End Get
    End Property

    Public Function GetUrl(topic As HelpTopic) As String
        Select Case topic
            Case HelpTopic.Home
                Return BaseUrl & "/"
            Case HelpTopic.T2x2Table
                Return BaseUrl & "/methods/2x2-table/"
            Case HelpTopic.BoxAndWhiskers
                Return BaseUrl & "/methods/box-and-whiskers/"
            Case HelpTopic.CategoricalHistogram
                Return BaseUrl & "/methods/categorical-histogram/"
            Case HelpTopic.CochranSQTest
                Return BaseUrl & "/methods/cochrans-q-test/"
            Case HelpTopic.ControlCharts
                Return BaseUrl & "/methods/control-charts/"
            Case HelpTopic.ConvexHull
                Return BaseUrl & "/methods/convex-hull-plot/"
            Case HelpTopic.CorrespondenceAnalysis
                Return BaseUrl & "/methods/correspondence-analysis/"
            Case HelpTopic.CoxRegression
                Return BaseUrl & "/methods/cox-regression/"
            Case HelpTopic.DescriptiveStatistics
                Return BaseUrl & "/methods/descriptive-statistics/"
            Case HelpTopic.DiscriminantAnalysis
                Return BaseUrl & "/methods/discriminant-analysis/"
            Case HelpTopic.FactorAnalysis
                Return BaseUrl & "/methods/factor-analysis/"
            Case HelpTopic.FriedmanTest
                Return BaseUrl & "/methods/friedman-test/"
            Case HelpTopic.GeneralizedEstimatingEquationsGEE
                Return BaseUrl & "/methods/generalized-estimating-equations-gee/"
            Case HelpTopic.GeneralizedLinearModelsGLM
                Return BaseUrl & "/methods/generalized-linear-models-glm/"
            Case HelpTopic.HierarchicalClustering
                Return BaseUrl & "/methods/hierarchical-clustering/"
            Case HelpTopic.Histogram
                Return BaseUrl & "/methods/histogram/"
            Case HelpTopic.HomogeneityOfVariance
                Return BaseUrl & "/methods/homogeneity-of-variance/"
            Case HelpTopic.HotellingSTSquaredTest
                Return BaseUrl & "/methods/hotellings-t-squared-test/"
            Case HelpTopic.IndependentProportions
                Return BaseUrl & "/methods/sample-size-independent-proportions/"
            Case HelpTopic.KaplanMeierPlot
                Return BaseUrl & "/methods/kaplan-meier-plot/"
            Case HelpTopic.KendallSRankCorrelation
                Return BaseUrl & "/methods/kendalls-rank-correlation/"
            Case HelpTopic.KiteChart
                Return BaseUrl & "/methods/kite-chart/"
            Case HelpTopic.KMeansClustering
                Return BaseUrl & "/methods/k-means-clustering/"
            Case HelpTopic.KruskalWallisTest
                Return BaseUrl & "/methods/kruskal-wallis-test/"
            Case HelpTopic.LogrankTest
                Return BaseUrl & "/methods/logrank-test/"
            Case HelpTopic.MannWhitneyTest
                Return BaseUrl & "/methods/mann-whitney-test/"
            Case HelpTopic.MantelHaenszelTest
                Return BaseUrl & "/methods/mantel-haenszel-test/"
            Case HelpTopic.MultinomialLogisticRegression
                Return BaseUrl & "/methods/multinomial-logistic-regression/"
            Case HelpTopic.MultipleCorrespondenceAnalysis
                Return BaseUrl & "/methods/multiple-correspondence-analysis/"
            Case HelpTopic.MultipleLinearRegressionLM
                Return BaseUrl & "/methods/multiple-linear-regression-lm/"
            Case HelpTopic.MultivariateControlCharts
                Return BaseUrl & "/methods/multivariate-control-charts/"
            Case HelpTopic.NegativeBinomialRegressionNB2
                Return BaseUrl & "/methods/negative-binomial-regression-nb2/"
            Case HelpTopic.NormalPlot
                Return BaseUrl & "/methods/normal-plot/"
            Case HelpTopic.NormalityTests
                Return BaseUrl & "/methods/normality-tests/"
            Case HelpTopic.OneWayANOVA
                Return BaseUrl & "/methods/one-way-anova/"
            Case HelpTopic.OneWayRepeatedMeasuresANOVA
                Return BaseUrl & "/methods/one-way-repeated-measures-anova/"
            Case HelpTopic.OrdinalLogisticRegression
                Return BaseUrl & "/methods/ordinal-logistic-regression/"
            Case HelpTopic.MixedModelsForRepeatedMeasuresMMRM
                Return BaseUrl & "/methods/mixed-models-for-repeated-measures-mmrm/"
            Case HelpTopic.LinearMixedModelsLMM
                Return BaseUrl & "/methods/linear-mixed-models-lmm/"
            Case HelpTopic.PropensityScoreMatching
                Return BaseUrl & "/methods/propensity-score-matching/"
            Case HelpTopic.PairedSingleSampleTTests
                Return BaseUrl & "/methods/paired-t-tests/"
            Case HelpTopic.PairedTTest
                Return BaseUrl & "/methods/sample-size-paired-t-test/"
            Case HelpTopic.Polarplot
                Return BaseUrl & "/methods/polar-plot/"
            Case HelpTopic.PrincipalComponentAnalysis
                Return BaseUrl & "/methods/principal-component-analysis/"
            Case HelpTopic.Proportions
                Return BaseUrl & "/methods/proportions/"
            Case HelpTopic.ROCCurve
                Return BaseUrl & "/methods/roc-curve/"
            Case HelpTopic.RxCTable
                Return BaseUrl & "/methods/rxc-table/"
            Case HelpTopic.ScatterPlotMatrix
                Return BaseUrl & "/methods/scatter-plot-matrix/"
            Case HelpTopic.SSlogrank
                Return BaseUrl & "/methods/sample-size-log-rank/"
            Case HelpTopic.SingleProportion
                Return BaseUrl & "/methods/sample-size-single-proportion/"
            Case HelpTopic.SkillingsMackTest
                Return BaseUrl & "/methods/skillings-mack-test/"
            Case HelpTopic.SpearmanRankCorrelation
                Return BaseUrl & "/methods/spearman-rank-correlation/"
            Case HelpTopic.Symmetry
                Return BaseUrl & "/methods/symmetry/"
            Case HelpTopic.TheilSenSimpleRegression
                Return BaseUrl & "/methods/theil-sen-simple-regression/"
            Case HelpTopic.TwoWayNestedANOVA
                Return BaseUrl & "/methods/two-way-nested-anova/"
            Case HelpTopic.UnivariateOutliers
                Return BaseUrl & "/methods/univariate-outliers/"
            Case HelpTopic.UnpairedTwoSampleTTests
                Return BaseUrl & "/methods/unpaired-two-sample-t-tests/"
            Case HelpTopic.UnpairedTTest
                Return BaseUrl & "/methods/sample-size-unpaired-t-test/"
            Case HelpTopic.SScox
                Return BaseUrl & "/methods/sample-size-cox-regression/"
            Case HelpTopic.SSicc
                Return BaseUrl & "/methods/sample-size-icc/"
            Case HelpTopic.SSblandaltman
                Return BaseUrl & "/methods/sample-size-bland-altman/"
            Case HelpTopic.ViolinPlot
                Return BaseUrl & "/methods/violin-plot/"
            Case HelpTopic.WilcoxonSignedRankTest
                Return BaseUrl & "/methods/wilcoxon-signed-rank-test/"
            Case HelpTopic.XYZ3DScatterplot
                Return BaseUrl & "/methods/xyz-3d-scatterplot/"
            Case HelpTopic.ZeroInflatedPoissonRegression
                Return BaseUrl & "/methods/zero-inflated-poisson-regression/"
            Case HelpTopic.PassingBablokRegression
                Return BaseUrl & "/methods/passing-bablok-regression/"
            Case HelpTopic.DemingRegression
                Return BaseUrl & "/methods/deming-regression/"
            Case HelpTopic.BlandAltman
                Return BaseUrl & "/methods/bland-altman/"
            Case HelpTopic.LinsCCC
                Return BaseUrl & "/methods/lins-ccc/"
            Case HelpTopic.CohensKappa
                Return BaseUrl & "/methods/cohens-kappa/"
            Case HelpTopic.IntraclassCorrelationCoefficients
                Return BaseUrl & "/methods/intraclass-correlation-coefficients/"
            Case HelpTopic.ExportChart
                Return BaseUrl & "/export-chart/"
            Case HelpTopic.GlobalSettings
                Return BaseUrl & "/global-settings/"
            Case Else
                Return FallbackBaseUrl
        End Select
    End Function

    ' Cache URL existence results to avoid repeated network requests
    Private ReadOnly _urlExistsCache As New Dictionary(Of String, Boolean)(StringComparer.OrdinalIgnoreCase)

    Public Sub OpenTopic(topic As HelpTopic)
        OpenUrlWithFallback(GetUrl(topic))
    End Sub

    Public Sub OpenUrl(url As String)
        If String.IsNullOrWhiteSpace(url) Then url = FallbackBaseUrl
        Dim psi As New ProcessStartInfo(url) With {.UseShellExecute = True}
        Process.Start(psi)
    End Sub

    Private Sub OpenUrlWithFallback(primaryUrl As String)
        If String.IsNullOrWhiteSpace(primaryUrl) Then
            OpenUrl(FallbackBaseUrl)
            Return
        End If

        ' 1) Try versioned URL first
        If UrlExistsCached(primaryUrl) Then
            OpenUrl(primaryUrl)
            Return
        End If

        ' 2) Try same relative path under /latest/
        Dim fallbackCandidate As String = BuildFallbackCandidate(primaryUrl)
        If Not String.IsNullOrWhiteSpace(fallbackCandidate) AndAlso UrlExistsCached(fallbackCandidate) Then
            OpenUrl(fallbackCandidate)
            Return
        End If

        ' 3) Last resort: open the fallback base
        OpenUrl(FallbackBaseUrl)
    End Sub

    Private Function BuildFallbackCandidate(primaryUrl As String) As String
        ' Preserve relative path when switching from /vX.Y.Z.W to /latest/
        Try
            Dim baseV As String = BaseUrl
            If String.IsNullOrWhiteSpace(baseV) Then Return Nothing
            If primaryUrl.StartsWith(baseV, StringComparison.OrdinalIgnoreCase) Then
                Dim rel As String = primaryUrl.Substring(baseV.Length)
                Dim fb As String = FallbackBaseUrl.TrimEnd("/"c)
                If Not rel.StartsWith("/", StringComparison.Ordinal) Then rel = "/" & rel
                Return fb & rel
            End If
        Catch
        End Try
        Return Nothing
    End Function

    Private Function UrlExistsCached(url As String) As Boolean
        Dim exists As Boolean
        If _urlExistsCache.TryGetValue(url, exists) Then Return exists
        exists = UrlExists(url)
        _urlExistsCache(url) = exists
        Return exists
    End Function

    Private Function UrlExists(url As String) As Boolean
        ' Use GET and sniff HTML because some hosting returns HTTP 200 for the MkDocs 404 page.
        Try
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 Or SecurityProtocolType.Tls11 Or SecurityProtocolType.Tls
        Catch
        End Try

        Try
            Dim req = CType(WebRequest.Create(url), HttpWebRequest)
            req.Method = "GET"
            req.AllowAutoRedirect = True
            req.Timeout = 2000
            req.ReadWriteTimeout = 2000
            req.UserAgent = "BESHStatNG-Help"
            req.Accept = "text/html"
            ' Try to read only a small portion of the response
            Try : req.AddRange(0, 8191) : Catch : End Try

            Using resp = CType(req.GetResponse(), HttpWebResponse)
                Dim code As Integer = CInt(resp.StatusCode)
                If code = 404 OrElse code = 410 Then Return False
                If code < 200 OrElse code >= 400 Then Return False

                Using s = resp.GetResponseStream()
                    If s Is Nothing Then Return False
                    Using sr As New IO.StreamReader(s, System.Text.Encoding.UTF8, detectEncodingFromByteOrderMarks:=True, bufferSize:=4096)
                        Dim html As String = sr.ReadToEnd()
                        If String.IsNullOrEmpty(html) Then Return True
                        Dim h As String = html.ToLowerInvariant()

                        ' MkDocs Material 404 markers
                        If h.Contains("oops! that page") OrElse
                            (h.Contains("page can") AndAlso h.Contains("t be found")) OrElse
                            h.Contains("404 - not found") OrElse
                            h.Contains(">404<") Then
                            Return False
                        End If

                        Return True
                    End Using
                End Using
            End Using

        Catch ex As WebException
            Dim resp = TryCast(ex.Response, HttpWebResponse)
            If resp IsNot Nothing Then
                Dim code As Integer = CInt(resp.StatusCode)
                If code = 404 OrElse code = 410 Then Return False
                Return False
            End If
            Return False
        Catch
            Return False
        End Try
    End Function
End Module
